; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_l476rg]
platform = ststm32
board = nucleo_l476rg
framework = stm32cube
board_build.stm32cube.custom_config_header = yes
extra_scripts = pre:hardfloat.py
build_flags =
    -DCFG_TUSB_MCU=OPT_MCU_STM32L4
    -I Src/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    -I Src/Middlewares/Third_Party/FreeRTOS/Source/include
    -I Src/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    -I Src/Middlewares/Third_Party/FatFs/src

[platformio]
include_dir = Inc
src_dir = Src
