; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_l476rg]
platform = ststm32
board = nucleo_l476rg
framework = stm32cube
board_build.stm32cube.custom_config_header = yes
extra_scripts = pre:hardfloat.py
board_build.ldscript = ldscript_app.ld
build_src_filter = +<*> +<../shared/*>
build_flags =
    -DCFG_TUSB_MCU=OPT_MCU_STM32L4
    -DFW_VERSION=1
    -D_RETARGET_LOCKING
    -I Inc
    -I Src
    -I Src/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    -I Src/Middlewares/Third_Party/FreeRTOS/Source/include
    -I Src/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    -I Src/Middlewares/Third_Party/FatFs/src
    -I shared

[env:bootloader]
platform = ststm32
board = nucleo_l476rg
framework = stm32cube
board_build.stm32cube.custom_config_header = yes
build_src_filter = +<../bootloader/src/*> +<../shared/*>
lib_ldf_mode = off
build_flags =
    -I bootloader/Inc
    -I bootloader/src
    -I shared
    -DBOOTLOADER_BUILD
board_build.ldscript = bootloader/ldscript_boot.ld

[platformio]
src_dir = Src
